$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        778:{
            items:3,
            nav:false
        },
        1100:{
            items:4,
            nav:true,
            loop:false
        }
    }
})